name: build

on:
  push:
    branches: [ master ] 

jobs:
  build-docker:
    name: Build docker container, tag and upload to registry    
    if: ${{ github.repository == 'armosec/host-sensor' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set name
        run: echo quay.io/armosec/kube-host-sensor:v1.0.${{ github.run_number }} > build_tag.txt

      - name: Build the Docker image
        run: docker build . --file build/Dockerfile --tag $(cat build_tag.txt) --build-arg run_number=${{ github.run_number }}

      - name: Re-Tag Image to latest
        run: docker tag $(cat build_tag.txt) quay.io/armosec/kube-host-sensor:latest

      - name: Login to Quay.io
        env: 
          QUAY_PASSWORD: ${{ secrets.QUAYIO_REGISTRY_PASSWORD }}
          QUAY_USERNAME: ${{ secrets.QUAYIO_REGISTRY_USERNAME }}
        run: docker login -u="${QUAY_USERNAME}" -p="${QUAY_PASSWORD}" quay.io
      - name: Push Docker image
        run: |
          docker push $(cat build_tag.txt)
          docker push quay.io/armosec/kube-host-sensor:latest